site_name: IHC - Grupo 8

repo_name: '2024.2-Grupo08'
repo_url: https://github.com/Interacao-Humano-Computador/2024.2-Grupo08


nav:
  - Home: index.md
  - Planejamento:
    - Heatmap: planejamento/heatmap.md
    - Cronograma: planejamento/cronograma.md
    - Metodologias: planejamento/metodologia.md
    - Ferramentas: planejamento/ferramentas.md
    - Sites Avaliados: planejamento/sitesAvaliados.md
    - Site Escolhido: planejamento/siteEscolhido.md
    - Processo de Design: planejamento/processoDesign.md
  - Análise de Requisitos:
    - Aspectos éticos: analiseRequisitos/aspEticos.md
    - Perfil do Usuário: analiseRequisitos/perfilUsuario.md
    - Personas: analiseRequisitos/personas.md
    - Cenários: analiseRequisitos/cenarios.md
    - Análise de tarefas:
        - Análise Hierárquica de Tarefas: analiseRequisitos/analise_tarefas/HTA.md
        - KLM: analiseRequisitos/analise_tarefas/KLM.md
    - Metas de usabilidades: analiseRequisitos/metasUsabilidade.md
    - Características Gerais: analiseRequisitos/caracGerais.md
    - Princípios Gerais: analiseRequisitos/principiosGerais.md
    - Guia de estilos: analiseRequisitos/guiaEstilos.md
  - Design, Avaliação e Desenvolvimento:
    - Nível 1:
      - Storyboard:
        - Planejamento da Avaliação do Storyboard: design_avaliacao/storyboard/planej-aval-story.md
        - Planejamento da Avaliação do Relato dos Resultados: design_avaliacao/storyboard/planj-aval-relato.md
        - Storyboards: design_avaliacao/storyboards.md
   

  - Verificação:
      - Verificação do Grupo:
          - Etapa 1:
              - Planejamento da Verificação da Etapa 1: verificacao/grupo/etapa1/planejamento-verificacao-etapa1.md
              - Cronograma: verificacao/grupo/etapa1/verificacao-cronograma.md
              - Ferramentas: verificacao/grupo/etapa1/verificacao-ferramentas.md
              - Processo de Design: verificacao/grupo/etapa1/verificacao-processo-design.md
              - Sites Avaliados: verificacao/grupo/etapa1/verificacao-sites-avaliados.md
              - Site Escolhido: verificacao/grupo/etapa1/verificacao-site-escolhido.md
              - Metodologia: verificacao/grupo/etapa1/verificacao-metodologia.md
          - Etapa 2:
              - Planejamento da Verificação da Etapa 2: verificacao/grupo/etapa2/verificacao-etapa2.md
              - Aspectos Éticos: verificacao/grupo/etapa2/aspectos-eticos.md
              - Análise de tarefas: verificacao/grupo/etapa2/verificacao-analiseTarefas.md
              - Perfil do Usuário: verificacao/grupo/etapa2/verificacao-perfil-usuario.md
          - Etapa 3:
              - Planejamento da Verificação da Etapa 3: verificacao/grupo/etapa2/verificacao-etapa3.md
              - Guia de estilos: verificacao/grupo/etapa2/verificacao-guia-de-estilo.md
              - Metas de Usabilidade: verificacao/grupo/etapa2/verificacao-metasUsab.md
              - Principios gerais: verificacao/grupo/etapa2/verificacao-principio-gerais.md
              - Características Gerais: verificacao/grupo/etapa2/verificacao-carac-gerais.md
      - Verificação do Grupo 01: 
          - Etapa 1:
              - Verificação da Etapa 1: verificacao/grupo/grupo01/etapa1/verificacao-etapa1.md
          - Etapa 2:
              - Verificação da Etapa 2: verificacao/grupo/grupo01/etapa2/verificacao-etapa2.md
          - Etapa 3:
              - Verificação da Etapa 3: verificacao/grupo/grupo01/etapa3/verificacao-etapa3.md

  - Reuniões:
    - Ata 01: atas/01.md
    - Ata 02: atas/02.md
    - Ata 03: atas/03.md
    - Ata 03: atas/03.md
  - Entregas:
    - Entrega 1: apresent/01.md 
    - Entrega 2: apresent/02.md 
    - Entrega 3: apresent/03.md 



theme:
  name: material
  language: pt
  logo: assets/logoDetran.png
  favicon: assets/logoPequena.png

  font:
    text: "Open Sans"
    code: "Source Code Pro"

  icon:
    admonition:
      <type>: material/alert-circle
    repo: fontawesome/brands/github

  palette:
      - scheme: default
        primary: blue
        accent: light blue
        toggle:
          icon: material/lightbulb
          name: Switch to dark mode
      - scheme: slate
        primary: blue
        accent: light blue
        toggle:
          icon: material/lightbulb-outline
          name: Switch to system preference


  features:
    - navigation.top
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.path
    - navigation.footer
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - search.highlight
    - search.share
    - search.suggest
    - navigation.instant
    - navigation.tracking
    - navigation.instant.progress

  extra_css:
    - stylesheets/custom.css

  plugins:
    - search
    - typeset
    - nav-extensions
    - glightbox
    - info

  markdown_extensions:
    - admonition
    - attr_list
    - def_list
    - md_in_html
    - tables
    - footnotes
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
    
